server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

          routes:
            - id: customer-service
              uri: lb://customer-service
              predicates:
                - Path=/api/v1/customers/**