spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/KULLANICI_ADIN/TELCO-CRM-PAIR6.git
          default-label: main
          search-paths: configs,configs/{application}
          clone-on-start: true
          force-pull: true

server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info