server:
  port: 9007

spring:
  application:
    name: billing-service
  datasource:
    url: jdbc:postgresql://localhost:5433/billing_db
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
  cloud:
    function:
      definition: subscriptionEvents;paymentEvents;usageEvents
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        subscriptionEvents-in-0:
          destination: telco.subscription.events
          group: billing-service
          content-type: application/json
        paymentEvents-in-0:
          destination: telco.payment.events
          group: billing-service
          content-type: application/json
        usageEvents-in-0:
          destination: telco.usage.events
          group: billing-service
          content-type: application/json
        billingEvents-out-0:
          destination: telco.billing.events
          content-type: application/json

outbox:
  publisher:
    poll-interval-ms: 5000
    batch-size: 20

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
